server.port=8080
server.address=0.0.0.0

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate auto-ddl
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Firebase
firebase.service-account-path=serviceAccountKey.json
